{{- $name := include "payment-api.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "payment-api.name" . }}
    chart: {{ template "payment-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    radius.app/application: {{ .Values.app.name }}
    radius.app/name: {{ .Values.app.svc.payment }}
data:
  all__EventBusConnection: {{ .Values.inf.eventbus.constr }}
  all__InstrumentationKey: "{{ .Values.inf.appinsights.key }}"
  all__UseAzureServiceBus: "{{ .Values.inf.eventbus.useAzure }}"