apiVersion: rad.app/v1
kind: Recipe
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  annotations:
    radius.app/application: {{ .Values.app.name }}
    radius.app/name: {{ .Values.app.infra.rabbitmq }}
spec:
  type: Applications.Messaging/rabbitMQQueues
