---
# Source: catalog-api/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-mychart-catalog-api"
  labels:
    app: catalog-api
    chart: catalog-api-0.1.0
    release: mychart
    heritage: Helm
data:
  catalog__ConnectionString: Server=sql-data;Initial Catalog=CatalogDb;User Id=sa;Password=Pass@word;TrustServerCertificate=true;
  catalog__PicBaseUrl: http:///webshoppingapigw/c/api/v1/catalog/items/[0]/pic/
  catalog__AzureStorageEnabled: "false"
  all__EventBusConnection: rabbitmq
  all__InstrumentationKey: ""
  all__UseAzureServiceBus: "false"
---
# Source: catalog-api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  labels:
    app: catalog-api
    chart: catalog-api-0.1.0
    release: mychart
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 81
      targetPort: grpc
      protocol: TCP
      name: grpc     
  selector:
    app: catalog-api
    release: mychart
---
# Source: catalog-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mychart-catalog-api
  labels:
    ufo: cfg-mychart-catalog-api
    app: catalog-api
    chart: catalog-api-0.1.0
    release: mychart
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
      release: mychart
  template:
    metadata:
      labels:
        app: catalog-api
        release: mychart
                   
    spec:
      
      containers:
        - name: catalog-api
          livenessProbe:
            httpGet:
              port: 80
              path: /liveness
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              port: 80
              path: /hc
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 5               
          image: "eshop/catalog.api:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: PATH_BASE
              value: /catalog-api
            - name: k8sname
              value: eshop-aks
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: OrchestratorType
              value: "K8S"
            - name: PORT
              value: "80"
            - name: GRPC_PORT
              value: "81"
            - name: ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: cfg-mychart-catalog-api
                  key: catalog__ConnectionString
            - name: PicBaseUrl
              valueFrom:
                configMapKeyRef:
                  name: cfg-mychart-catalog-api
                  key: catalog__PicBaseUrl
            - name: AzureStorageEnabled
              valueFrom:
                configMapKeyRef:
                  name: cfg-mychart-catalog-api
                  key: catalog__AzureStorageEnabled
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                configMapKeyRef:
                  name: cfg-mychart-catalog-api
                  key: all__InstrumentationKey
            - name: EventBusConnection
              valueFrom:
                configMapKeyRef:
                  name: cfg-mychart-catalog-api
                  key: all__EventBusConnection
            - name: AzureServiceBusEnabled
              valueFrom:
                configMapKeyRef:
                  name: cfg-mychart-catalog-api
                  key: all__UseAzureServiceBus
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: grpc
              containerPort: 81
              protocol: TCP              
          resources:
            {}
